// only export components here because they will be registered into the pipeline
export { default as advancedWheelsDebug } from '@/modules/apps/advancedWheelsDebug/app.vue'
export { default as brakeTorqueGraph } from '@/modules/apps/brakeTorqueGraph/app.vue'
export { default as busLine } from '@/modules/apps/busLine/app.vue'
export { default as cameraDistance } from '@/modules/apps/cameraDistance/app.vue'
export { default as clutchThermalDebug } from '@/modules/apps/clutchThermalDebug/app.vue'
export { default as compass } from '@/modules/apps/compass/app.vue'
export { default as compassPrecise } from '@/modules/apps/compassPrecise/app.vue'
export { default as damageApp } from '@/modules/apps/damageAppVehicleSimple/app.vue'
export { default as dragRace } from '@/modules/apps/dragRace/app.vue'
export { default as engineDebug } from '@/modules/apps/engineDebug/app.vue'
export { default as engineDynamometer } from '@/modules/apps/engineDynamometer/app.vue'
export { default as engineHeatDebugGraph } from '@/modules/apps/engineHeatDebugGraph/app.vue'
export { default as engineThermalDebug } from '@/modules/apps/engineThermalDebug/app.vue'
export { default as forcedInduction } from '@/modules/apps/forcedInduction/app.vue'
export { default as forcedInductionDebug } from '@/modules/apps/forcedInductionDebug/app.vue'
export { default as hydraulicsDebug } from '@/modules/apps/hydraulicsDebug/app.vue'
export { default as keyList } from '@/modules/apps/keys/app.vue'
export { default as logvehiclestats } from '@/modules/apps/logVehicleStats/app.vue'
// export { default as multiAppContainer } from '@/modules/apps/multiAppContainer/app.vue'
export { default as simpleDigTacho } from '@/modules/apps/simpleDigTacho/app.vue'
export { default as tacho2 } from '@/modules/apps/tacho2/app.vue'
export { default as tasklist } from '@/modules/apps/tasklist/app.vue'
